[alice]
Q = {t = 2, m = [{n = "bob"}, {n = "carol"}, {n = "dave"}]}

[bob]
Q = {t = 2, m = [{n = "alice"}, {n = "carol"}, {n = "dave"}]}

[carol]
Q = {t = 2, m = [{n = "alice"}, {n = "bob"}, {n = "dave"}]}

[dave]
Q = {t = 2, m = [{n = "alice"}, {n = "bob"}, {n = "carol"}]}
