[alice]
Q = {t = 1, m = [{q = {t = 2, m = [{n = "bob"}, {n = "carol"}]}},
                 {q = {t = 2, m = [{n = "dave"}, {n = "elsie"}]}}]}

[bob]
Q = {t = 2, m = [{n = "alice"}, {n = "carol"}]}

[carol]
Q = {t = 2, m = [{n = "alice"}, {n = "bob"}]}

[dave]
Q = {t = 2, m = [{n = "alice"}, {n = "elsie"}]}

[elsie]
Q = {t = 2, m = [{n = "alice"}, {n = "dave"}]}
